#!/bin/bash

TESTDIR=tests
cd ..

java DriverHW02 -m Michael names/*.csv >> $TESTDIR/my_Michael.txt
java DriverHW02 -m Aaden names/*.csv >> $TESTDIR/my_Aaden.txt
java DriverHW02 -f Ada names/*.csv >> $TESTDIR/my_Ada.txt
java DriverHW02 -f Kira names/*.csv >> $TESTDIR/my_Kira.txt
java DriverHW02 -f Kira -m Michael names/names2*.csv > $TESTDIR/my_KiraMichael2000.txt


cd $TESTDIR

DIFF_ONE=$(diff my_Michael.txt Michael.txt)
DIFF_TWO=$(diff my_Aaden.txt Aaden.txt)
DIFF_THREE=$(diff my_Ada.txt Ada.txt)
DIFF_FOUR=$(diff my_Kira.txt Kira.txt)
DIFF_FIVE=$(diff my_KiraMichael2000.txt KiraMichael2000.txt)

if [ "$DIFF_ONE" == "" ] && [ "$DIFF_TWO" == "" ] && [ "$DIFF_THREE" == "" ] && [ "$DIFF_FOUR" == "" ] && [ "$DIFF_FIVE" == "" ]
then
    echo "No errors in testing!"
else
    if [ "$DIFF_ONE" != "" ]
       then
	   echo "Errors exist in Michael test"
    fi
    if [ "$DIFF_TWO" != "" ]
       then
	   echo "Errors exist in Aaden test"
    fi
    if [ "$DIFF_THREE" != "" ]
       then
	   echo "Errors exist in Ada test"
    fi
    if [ "$DIFF_FOUR" != "" ]
       then
	   echo "Errors exist in Kira test"
    fi
    if [ "$DIFF_FIVE" != "" ]
       then
	   echo "Errors exist in KiraMichael2000 test"
    fi	  
fi

rm my*.txt



